### ISSUE TITLE
想问一下红米ax3000真的能刷吗，年初试过跳线也没弄成

### ISSUE THREAD

**Issue by 21064321** [NakanoSanku/StudyShare#1]
1

**Comment by NakanoSanku** [comment]
理论上是可行的，且恩山也有成功案例，不过ax3000刷机意义不大，建议更换设备

**Comment by 21064321** [comment]
> 理论上是可行的，且恩山也有成功案例，不过ax3000刷机意义不大，建议更换设备

搜过恩山，但是没找到相关帖子，能指明一下嘛，苦逼大学生没钱买ax6000，有机会上6000现在还是想玩玩openwrt

**Comment by NakanoSanku** [comment]
你刷机的目的是什么，ax3000刷机几乎不能改变什么，我建议卖掉换成7981的机子，价格差不了一顿饭钱，实在想刷就按照cr880x系列的刷机方法刷就可以了

**Comment by 21064321** [comment]
> 你刷机的目的是什么，ax3000刷机几乎不能改变什么，我建议卖掉换成7981的机子，价格差不了一顿饭钱，实在想刷就按照cr880x系列的刷机方法刷就可以了

好的，谢谢指教
